### DISCUSSION TITLE
Customise the rendering component

### DISCUSSION THREAD

**Discussion by AaronLayton** [code-hike/codehike#131] [Q&A]
I am using `mdx-bundler` and previously I was picking up on `<pre>` tag and replacing that with my own custom `<SyntaxHighter />`. In my component I am doing a few extra effects that help with styling, code copying etc.

Is there a way to customise the rendered output element so I can decorate it with my own container styles instead of the 3 dots in the top left?

**Comment by pomber** [comment]
You can change the styles using CSS. For example you could hide the dots with:

```css
.ch-frame-button {
  border-color: #5c5c5c !important;
  background-color: #535353 !important;
}
```

You can't customize the HTML. I may add a "copy" button soon, what other things are you trying to add?
