### DISCUSSION TITLE
Override width of code panel in Spotlight

### DISCUSSION THREAD

**Discussion by zaphod72** [code-hike/codehike#290] [Q&A] [answered]
Hi.
Is it possible to override the Spotlight code panel width?

TIA

**Comment by pomber** [comment, marked as answer]
you can change the width of `.ch-spotlight-sticker`

```css
.ch-spotlight-sticker {
  width: 300px;
}
```
