### DISCUSSION TITLE
Is it possible to display the language of the code block in the top right corner of the code block?

### DISCUSSION THREAD

**Discussion by codersjj** [code-hike/codehike#405] [Q&A] [answered]
Like this: 
![image](https://github.com/code-hike/codehike/assets/44868357/03e33016-6312-4e63-a61b-551ce734a5e6)
see: https://vuejs.org/guide/introduction.html#single-file-components

**Comment by pomber** [comment, marked as answer]
You can try something like this with CSS:

```css
.ch-codeblock [data-ch-lang]::after{
  content: attr(data-ch-lang);
  position: absolute;
  right: 10px;
  top: 10px;
}
```

[playground](https://play.codehike.org/#N4IgtgJgHiBcIB0B2BiABACQKYBscHtlkBRCASwBc0wsA6IpAA2YAcBPZdMAQwCcBrANoBGAGywATABYAusha8ySCgAoEIACoALMgGc0etAGF8ELJjL8s6gJTJmjBiAA0IAMa7dcELQVYAbmRYAO4AtG74ytxKWLxowGjIaNR8AOZKsGgAHCxQANyJSAC+DLRuWuGmWABGBG78aIIQ3BTc4RU43EipMrCw3ABmFLHASWgRyljKmS0UvCrNre2hnd02eWMs+LqUZJEz1br4OACuwxtIyYqpWhSZwgAMuRfJFPgs90-5yEUu7pEDMipOCgHAxAByJzA1ViXlgA24OF0WFcui0+GCJnYACEzm8kHAEUiUSBuGd8AAZJT8QmI5GuChaLA0bw8YaKRGhZoCWIgIpFIA)

**Reply by codersjj** [reply]
Thank you for your answer, it's very helpful! Based on this, I added a few more lines of CSS to implement the effect when there is a copy button:

```CSS
.ch-codeblock [data-ch-lang] + .ch-code-button,
.ch-codeblock [data-ch-lang]:has(+ .ch-code-button):hover::after,
.ch-codeblock:has([data-ch-lang] + .ch-code-button:hover) [data-ch-lang]::after {
  opacity: 0;
}

.ch-codeblock [data-ch-lang]:hover + .ch-code-button,
.ch-codeblock [data-ch-lang] + .ch-code-button:hover {
  opacity: 1;
}

.ch-codeblock [data-ch-lang] + .ch-code-button {
  transition: opacity .5s ease;
}
```

see: [playground](https://play.codehike.org/#N4IgtgJgHiBcIB0B2BiABACQKYBscHtlkBRCASwBc0wsA6IpAA2YAcBPCgC3yWXTACGAJwDWAbQCMANlgAmACwBdZCyFkkFABQIQAFU5kAzmiNoAwvghZMZEVh0BKZM0YMQAGhABjQ4bghaVSwANzIsAHcAWi8eCgF1LCE0YDRkNGphAHN1WDQADhYoAG5UpABfBlovTmjLLAAjAi8RNDEIATjompwBJEzFWFgBADMKROA0tBiNLA1cjoohTXbO6sievociyZZ8Q0oyHnn6w3wcAFcx7aR0tUzOClyJAAZC6-SKfBYn1+LkCt4gKqNRiVka+GarRWAi6616-TQAGo0MDalZIvVLp8kO5kKjQQ0mi02h0YWsNv1YJwBIZNMj8XUMVieA4qfhgolBiMxkJcUgGWCiVSaZoSatuvDFEiUWsCUyKNi2RyhA4oaTYRSBkNRolkpMvgIvJQ2LlntcAXjZXVwZCxWSJX0BtxldKBVh5di+W6bcToRrJa6rejMQqjs7dRMbmgDUaKCa0BJzZUg4SIb71eSA-SUx6eHqo4tevsKIckLkY8aUQBWYxYGlYc0ebw8YZkTJwUA4BIAOXOYHqiT8sGGAhwhiwnkM3HCFnYACFmUg4ItzhOQAJLvgADLqERwEdjtdcLA0fyCHlkUeRdqiRIgMplIA)
