### ISSUE TITLE
spotlight with horizontal tab controls?

### ISSUE THREAD

**Issue by DanielFGray** [code-hike/codehike#198]
I love the spotlight transition effects, but I wondered if it's possible to mark some individual spotlight blocks for horizontal controls with my own css?

**Comment by pomber** [comment]
Haven't tried, but it's a flex container so changing `flex-direction` should get you halfway there. 

But I would take a look later, it's a very valid use case and I want to reduce the css required to style it.

**Comment by pomber** [comment]
Here is a [quick example](https://play.codehike.org/#N4IgtgJgHiBcIB0B2BiABACQKYBscHtlkBRCASwBc0wsA6IpAHgGENaBlAB3wpzIHMAFhQB8DAAaTOATwqD8SNINwFaM5OjABDAE4BrANoBGAGywATABYAusk46ySCgAoEIACqCyAZzQ+0zPgQWJhkelhuAJTIkuLIALSJElKy8orKePhq0mgAZvgAxgCu3gC8RsawAKy2SLEM9o5UuUVIBRRkCgyJ8cniMnIKSipZMnmFJeUGAOwWNjGSDAUKFFhODMiMAPSsHNy8AsJiSMggADQgBd7ecCBqOlgAbmRYAO7xy05ajlg6aMBoZBoai6fiOWBoAAcnCgAG5AUgAL4MWgFQTxbz7PhCKjAIF5HBYKDxcgPdqdJAQ5Y4IpgJCw5DIk5IVHozE8bHCeIULQAI18eMUBKJJLIZI6CghOnwrwZQv4Wk4EKM5hhcuB2h0YKQ8QcOIhAAY1YyUWiMVjDhRuXz-vjNdrDeq0JwtBByEh+BDLDCocakaa2Racdbec7bUL7eC0Aa5UzkKzzRzLRiOgVwn9BcDXmQIHIIVoihR8LHzpcFLkBHBQHwkFgAHK03m-G6wXJaHDeLAXbzyV6BGQAIULRaQcDbHa7IDkWBot20qwc7ZJunTIERiKAA).

You can start with this css: 
```css

.ch-spotlight {
  flex-direction: column;
}

.ch-spotlight-tabs {
  flex-direction: row;
  gap: 12px;
  margin-right: 0px;
}

.ch-spotlight-tab {
  margin: 0;
  padding: 4px 8px;
}

.ch-spotlight-tab p {
  margin: 0;
}

.ch-spotlight-sticker {
  width: auto;
}
```
