### ISSUE TITLE
[smooth-code] Wrong line width with different font-family

### ISSUE THREAD

**Issue by pomber** [code-hike/codehike#79]
A css like this (from tailwind):

```css
code {
  font-family: ui-monospace, SFMono-Regular, Consolas,
    "Liberation Mono", Menlo, monospace;
}
```

breaks the line width calculation (see code-spring>longer story)
